btorvis: robust-ified, added support for evince
(also: eliminated all tabs found)

diff --git a/contrib/btorvis b/contrib/btorvis
--- a/contrib/btorvis
+++ b/contrib/btorvis
@@ -1,26 +1,98 @@
 #!/bin/sh
-if [ $# -gt 1 ]; then
-  echo "Usage: ./btorvis.sh <filename>"
-  exit 1
-fi
-temp=/tmp/btorvis$$
-pstemp=$temp".ps"
-pdftemp=$temp".pdf"
+
+readonly TMPDIR=/tmp
+readonly TMPFILE_NAME=btorvis$$
+
+readonly tmpfile_pdf="$TMPDIR/$tmpfile_name".pdf
+readonly tmpfile_ps="$TMPFILE_NAME".ps
+
+inputfile=unknown
+pdfreader=unknown
+ps2pdf=ps2pdf
 btor2dot=unknown
-for d in `echo $PATH|sed -e 's,:, ,g'` .
-do
-  file=$d/btor2dot
-  [ -d $d ] || continue
-  [ -f $file ] || continue
-  btor2dot=$file
-  break
-done
-if [ $btor2dot = unknown ]
-then
-  echo "*** btorvis: can not find 'btor2dot'" 1>&2
+
+
+function info
+{
+  echo "*** btorvis: $1"
+}
+
+function die
+{
+  info "$1"
   exit 1
+}
+       
+while [ $# -gt 0 ]
+do
+  case $1 in
+        -h|--help) echo -e "usage: btorvis [ -h | --help ] <file> \n"
+                   exit 0;;
+        *)         break;;
+  esac
+  shift
+done
+
+if [ $# -gt 1 ]; then
+  die "invalid number of arguments: '$#'"
 fi
-cat $*|$btor2dot | dot -Tps2 > $pstemp
-ps2pdf $pstemp $pdftemp || exit 1
-acroread $pdftemp
-rm -f $pstemp $pdftemp
+
+inputfile="$*"
+if [ ! -f $inputfile ]; then
+  die "invalid input file: '$inputfile'"
+fi
+
+btor2dot=$(readlink -f "./btor2dot")
+if [ ! -f $btor2dot ]; then
+  btor2dot=$(readlink -f "./contrib/btor2dot")
+  if [ ! -f $btor2dot ]; then
+    for d in `echo $PATH|sed -e 's,:, ,g'` .
+    do
+      file=$d/btor2dot
+      [ -d $d ] || continue
+      [ -f $file ] || continue
+      btor2dot=$file
+      break
+    done
+  fi
+  if [ ! -f $btor2dot ]; then
+    die "could not find 'btor2dot'"
+  fi
+fi
+
+ps2pdf=$(which "$ps2pdf")
+
+if [ $? = 1 ]; then
+  die "could not find 'ps2pdf'"
+fi
+
+for pdfreader in "evince" "acroread"; do
+  which "$pdfreader"
+  if [ $? = 0 ]; then
+    break
+  fi
+done
+
+if [ x"$pdfreader" = xunknown ]; then
+  die "no pdf reader found"
+fi
+
+
+## run
+
+info "generating dot file"
+cat "$inputfile" | $btor2dot | dot -Tps2 > $tmpfile_ps
+
+info "generation pdf file"
+$ps2pdf $tmpfile_ps $tmpfile_pdf
+if [ $? = 1 ]; then
+  die "failed to generate pdf file"
+fi
+
+"$pdfreader" $tmpfile_pdf
+
+
+## cleanup
+
+rm -f $tmpfile_ps $tmpfile_pdf
+exit 0
diff --git a/contrib/fuzztestboolector b/contrib/fuzztestboolector
--- a/contrib/fuzztestboolector
+++ b/contrib/fuzztestboolector
@@ -73,13 +73,13 @@ update=0
 while getopts "i:c:nrs:v:" o
 do
   case "$o" in
-  i)	id=$OPTARG;;
-  c)	cov=1; covlimit=$OPTARG;;
-  n)	covcleanup=0;;
-  r)	crosscheck=1;;
+  i)    id=$OPTARG;;
+  c)    cov=1; covlimit=$OPTARG;;
+  n)    covcleanup=0;;
+  r)    crosscheck=1;;
   s)    stats=1; update=$OPTARG;;
   v)    valgrindcheck=$OPTARG;;
-  [?])	echo "$usage" 1>&2; exit 1;;
+  [?])  echo "$usage" 1>&2; exit 1;;
   esac
 done
 
@@ -117,9 +117,9 @@ do
   randomnumber=$RANDOM
   ((randomnumber %= 3))
   case $randomnumber in
-  0)	uamode=uag;;
-  1)	uamode=ual;;
-  2)	uamode=uali;;
+  0)    uamode=uag;;
+  1)    uamode=ual;;
+  2)    uamode=uali;;
   esac
 
   randomnumber=$RANDOM
@@ -133,10 +133,10 @@ do
   randomnumber=$RANDOM
   ((randomnumber &= 3))
   case $randomnumber in
-  0)	uaenc=uaz;;
-  1)	uaenc=uao;;
-  2)	uaenc=uas;;
-  3)	uaenc=uac; uabwref=uad;;     # uac needs uad
+  0)    uaenc=uaz;;
+  1)    uaenc=uao;;
+  2)    uaenc=uas;;
+  3)    uaenc=uac; uabwref=uad;;     # uac needs uad
   esac
 
   ua=$RANDOM
@@ -224,11 +224,11 @@ do
     if [[ "$rwl" -eq 3 ]]; then 
       goldenresult=$result
       if [[ "$goldenresult" != sat ]] && [[ "$goldenresult" != unsat ]]; then
-	echo "ERROR"
-	cp "$file" error${id}.$suffix
-	echo "error: $callstring" > $errtxtfile
-	cleanup
-	exit 1
+        echo "ERROR"
+        cp "$file" error${id}.$suffix
+        echo "error: $callstring" > $errtxtfile
+        cleanup
+        exit 1
       fi
       if [[ "$crosscheck" -eq 1 ]]; then
         if [[ $suffix == smt ]]; then
@@ -239,67 +239,67 @@ do
           echo "INTERNAL ERROR"
           exit 1
         fi
-	if [[ "$goldenresult" != "$result" ]]; then
-	  echo "ERROR"
-	  cp "$file" error${id}.$suffix
-	  echo "error: $callstring" > "$errtxtfile"
+        if [[ "$goldenresult" != "$result" ]]; then
+          echo "ERROR"
+          cp "$file" error${id}.$suffix
+          echo "error: $callstring" > "$errtxtfile"
           echo "boolector-0.4 yields different result" >> "$errtxtfile"
           if [[ $suffix != btor ]]; then
             echo "after converting file to BTOR" >> "$errtxtfile"
           fi
-	  cleanup
-	  exit 1
-	fi
+          cleanup
+          exit 1
+        fi
       fi
     else
       if [[ "$goldenresult" != "$result" ]]; then
-	echo "ERROR"
-	cp "$file" error${id}.$suffix
-	echo "error: $callstring" > "$errtxtfile"
-	echo "golden result: $goldenresult" >> "$errtxtfile"
-	echo "actual result: $result" >> "$errtxtfile"
-	cleanup
-	exit 1
+        echo "ERROR"
+        cp "$file" error${id}.$suffix
+        echo "error: $callstring" > "$errtxtfile"
+        echo "golden result: $goldenresult" >> "$errtxtfile"
+        echo "actual result: $result" >> "$errtxtfile"
+        cleanup
+        exit 1
       fi
     fi 
 
     if [[ "$cov" -eq 1 ]]; then
       if [[ ! -s "$stderror" ]]; then
-	rm "$stderror"
+        rm "$stderror"
       else
         cat "$stderror" | sort | uniq > "$filetmp"
-	hashsum=`md5sum "$filetmp" | awk '{ print $1 }'`
+        hashsum=`md5sum "$filetmp" | awk '{ print $1 }'`
         # synchronization for parallel usage
-	( flock -x 200 
-	  numcovtests=`cat "$filecovhashes" | wc -l`
-	  if [[ "$numcovtests" -eq "$covlimit" ]]; then
-	    exit 2
-	  fi
-	  if [[ `grep -c "^$hashsum" "$filecovhashes"` -eq 0 ]]; then
-	    echo "$hashsum" >> "$filecovhashes"
-	    exit 1
-	  else
-	    exit 0
-	  fi 
-	) 200> "$filecovlock"
-	retval=$?
+        ( flock -x 200 
+          numcovtests=`cat "$filecovhashes" | wc -l`
+          if [[ "$numcovtests" -eq "$covlimit" ]]; then
+            exit 2
+          fi
+          if [[ `grep -c "^$hashsum" "$filecovhashes"` -eq 0 ]]; then
+            echo "$hashsum" >> "$filecovhashes"
+            exit 1
+          else
+            exit 0
+          fi 
+        ) 200> "$filecovlock"
+        retval=$?
 
-	if [[ "$retval" -eq 2 ]]; then
-	  cleanup
-	  rm "$stderror"
-	  exit 0
-	fi
+        if [[ "$retval" -eq 2 ]]; then
+          cleanup
+          rm "$stderror"
+          exit 0
+        fi
 
-	if [[ "$retval" -eq 1 ]]; then
-	  cp "$filetmp" "$stderror"
-	  callfile=${covbase}.cs
-	  covtestfile=${covbase}.btor
-	  echo ${callstring/" $file"/""} > "$callfile"
-	  cp "$file" "$covtestfile"
-	  ((covtestcounter++))
-	else
-	  rm "$stderror"
-	fi
+        if [[ "$retval" -eq 1 ]]; then
+          cp "$filetmp" "$stderror"
+          callfile=${covbase}.cs
+          covtestfile=${covbase}.btor
+          echo ${callstring/" $file"/""} > "$callfile"
+          cp "$file" "$covtestfile"
+          ((covtestcounter++))
+        else
+          rm "$stderror"
+        fi
       fi
     fi
 
