ddcrossboolector: fixed handling of cmd args

diff --git a/contrib/ddcrossboolector b/contrib/ddcrossboolector
--- a/contrib/ddcrossboolector
+++ b/contrib/ddcrossboolector
@@ -6,24 +6,38 @@ die ()
   exit 1
 }
 
-trap "exit" SIGHUP SIGINT SIGTERM
+trap "exit 2" SIGHUP SIGINT SIGTERM
 
 btor_test=""
+btor_test_opts=""
 btor_ref=""
+btor_ref_opts=""
 
 while [ $# -gt 0 ]
 do
   case $1 in
     -h|--help)
-      echo "usage: $(basename $0) [<option>] <test> <ref> <file>"
+      echo -n "usage: $(basename $0) [<option>] <test> [<testopts>] <ref> "
+      echo "[<refopts>] <file>"
       echo
-      echo "  <test>: the solver instance under test"
-      echo "  <ref>:  the reference solver instance"
+      echo "  <test>:     the solver instance under test"
+      echo "  <testopts>: options passed to <test>"
+      echo "  <ref>:      the reference solver instance"
+      echo "  <refopts>:  options passed to <ref>"
       echo
       echo "  options:"
       echo "    -h, --help    print this message and exit"
       echo
       exit
+      ;;
+    -*|[0-9]*) 
+      if [ x"$btor_test" = x ]; then
+	die "invalid option: $1"
+      elif [ x"$btor_ref" = x  ]; then
+	btor_test_opts="$btor_test_opts $1"
+      else
+	btor_ref_opts="$btor_ref_opts $1"
+      fi
       ;;
     *) 
       if [ x"$btor_test" = x ]; then
@@ -42,12 +56,12 @@ inputfile="$*"
 
 [ x"$inputfile" = x ] && die "inputfile missing"
 
-$btor_ref $inputfile > /dev/null 2>&1
+$btor_ref $btor_ref_opts $inputfile > /dev/null 2>&1
 expected_result=$?
 #echo "$btor_ref"
 #echo "expected result: $expected_result"
 
-$btor_test $inputfile > /dev/null 2>&1
+$btor_test $btor_test_opts $inputfile > /dev/null 2>&1
 result=$?
 #echo "$btor_test"
 #echo "result: $result"
