improved

diff --git a/contrib/testbtorbtorgen b/contrib/testbtorbtorgen
--- a/contrib/testbtorbtorgen
+++ b/contrib/testbtorbtorgen
@@ -1,6 +1,6 @@
 #!/bin/bash
 i=0
-file="/tmp/test$$btor"
+file="/tmp/test$$.btor"
 while true 
 do 
   ((i++))
@@ -14,20 +14,15 @@ do
     rm -f $file
     exit
   fi
-  echo -n "Test "$i" (rwl1): "
-  boolector -rwl1 $file 
-  if [[ $? -ne $retval ]]; then
-    echo "ERROR"
-    cp $file ./error.btor
-    rm -f $file
-    exit
-  fi 
-  echo -n "Test "$i" (rwl0): "
-  boolector -rwl0 $file 
-  if [[ $? -ne $retval ]]; then
-    echo "ERROR"
-    cp $file ./error.btor
-    rm -f $file
-    exit
-  fi 
+  for rwl in "rwl1" "rwl0"
+  do
+    echo -n "Test $i ($rwl): "
+    boolector -$rwl $file 
+    if [[ $? -ne $retval ]]; then
+      echo "ERROR"
+      cp $file ./error.btor
+      rm -f $file
+      exit
+    fi 
+  done
 done
