added picosat configuration

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,11 +4,13 @@ debug=unknown
 precosat=unknown
 lingeling=unknown
 minisat=unknown
+picosat=unknown
 arch=unknown
 
 onlyprecosat=no
 onlylingeling=no
 onlyminisat=no
+onlypicosat=no
 
 #--------------------------------------------------------------------------#
 
@@ -38,18 +40,21 @@ the binary if they can be found in the parent directory.
 
 By specifying one of them 'configure' fails if it can not be used.
 
+  --picosat         use and link with PicoSAT
   --precosat        use and link with PrecoSAT
   --lingeling       use and link with Lingeling
   --minisat         use and link with MiniSAT
 
 To disable some of them use the following options:
 
+  --no-picosat      do not use PicoSAT
   --no-precosat     do not use PrecoSAT
   --no-lingeling    do not use Lingeling
   --no-minisat      do not use Lingeling
 
 In addition PicoSAT is always required as default back end SAT solver.
 
+  --only-picosat    only use and link with PicoSAT
   --only-precosat   only use and link with PrecoSAT
   --only-lingeling  only use and link with Lingeling
   --only-minisat    only use and link with MiniSAT
@@ -69,12 +74,15 @@ do
     -O) debug=no;;
     -m32|--m32) arch=32;;
     -m64|--m64) arch=64;;
+    -picosat|--picosat) picosat=yes;;
     -precosat|--precosat) precosat=yes;;
     -lingeling|--lingeling) lingeling=yes;;
     -minisat|--minisat) minisat=yes;;
+    -no-picosat|--no-picosat) picosat=no;;
     -no-precosat|--no-precosat) precosat=no;;
     -no-lingeling|--no-lingeling) lingeling=no;;
     -no-minisat|--no-minisat) minisat=no;;
+    -only-picosat|--only-picosat) onlypicosat=yes;;
     -only-precosat|--only-precosat) onlyprecosat=yes;;
     -only-lingeling|--only-lingeling) onlylingeling=yes;;
     -only-minisat|--only-minisat) onlyminisat=yes;;
@@ -86,12 +94,29 @@ done
 
 #--------------------------------------------------------------------------#
 
+if [ $onlypicosat = yes ]
+then
+  [ $picosat = yes ] && \
+    die "can not combine '--only-picosat' with '--picosat'"
+  [ $precosat = yes ] && \
+    die "can not combine '--only-picosat' with '--precosat'"
+  [ $minisat = yes ] && \
+    die "can not combine '--only-picosat' with '--minisat'"
+  picosat=yes;
+  precosat=no
+  lingeling=no
+  minisat=no
+fi
+
 if [ $onlylingeling = yes ]
 then
+  [ $picosat = yes ] && \
+    die "can not combine '--only-lingeling' with '--picosat'"
   [ $precosat = yes ] && \
     die "can not combine '--only-lingeling' with '--precosat'"
   [ $minisat = yes ] && \
     die "can not combine '--only-lingeling' with '--minisat'"
+  picosat=no;
   lingeling=yes
   precosat=no
   minisat=no
@@ -99,10 +124,13 @@ fi
 
 if [ $onlyprecosat = yes ]
 then
+  [ $picosat = yes ] && \
+    die "can not combine '--only-precosat' with '--picosat'"
   [ $lingeling = yes ] && \
     die "can not combine '--only-precosat' with '--lingeling'"
   [ $minisat = yes ] && \
     die "can not combine '--only-precosat' with '--minisat'"
+  picosat=no;
   lingeling=no
   precosat=yes
   minisat=no
@@ -110,10 +138,13 @@ fi
 
 if [ $onlyminisat = yes ]
 then
+  [ $picosat = yes ] && \
+    die "can not combine '--only-minisat' with '--picosat'"
   [ $lingeling = yes ] && \
     die "can not combine '--only-minisat' with '--lingeling'"
   [ $precosat = yes ] && \
     die "can not combine '--only-minisat' with '--precosat'"
+  picosat=no;
   lingeling=no
   precosat=no
   minisat=yes
@@ -169,23 +200,42 @@ LIBSTDCPP=no
 
 #--------------------------------------------------------------------------#
 
-if [ -d ../picosat ]
+if [ $picosat = no ]
 then
-  for path in ../picosat/picosat.o ../picosat/version.o allfound
-  do
-    [ -f $path ] || break
-  done
-else
-  path=../picosat
-fi
+  msg "not using PicoSAT as requested by command line option"
 
-if [ $path = allfound ]
-then
-  msg "using PicoSAT in '../picosat'"
-  [ X"$OBJS" = X ] || OBJS="$OBJS "
-  OBJS="${OBJS}../picosat/picosat.o ../picosat/version.o"
 else
-  die "PicoSAT not found: '$path' missing"
+
+  if [ -d ../picosat ]
+  then
+    for path in ../picosat/picosat.o ../picosat/version.o allfound
+    do
+      [ -f $path ] || break
+    done
+  else
+    path=../picosat
+  fi
+
+  if [ $path = allfound ]
+  then
+    msg "using PicoSAT in '../picosat'"
+    [ X"$OBJS" = X ] || OBJS="$OBJS "
+    picosat=yes
+  elif [ $picosat = yes ]
+  then
+    die "impossible to use PicoSAT: '$path' missing"
+  else
+    msg "disabling PicoSAT: '$path' missing"
+    picosat=no
+  fi
+
+  if [ $picosat = yes ]
+  then
+    [ X"$CFLAGS" = X ] || CFLAGS="$CFLAGS"
+    [ X"$OBJS" = X ] || OBJS="$OBJS"
+    CFLAGS="${CFLAGS}-DBTOR_USE_PICOSAT"
+    OBJS="${OBJS}../picosat/picosat.o ../picosat/version.o"
+  fi
 fi
 
 #--------------------------------------------------------------------------#
@@ -329,6 +379,11 @@ else
   fi
 
 fi
+
+#--------------------------------------------------------------------------#
+
+[ $picosat = no -a $lingeling = no ] && \
+  die "could not find PicoSAT nor Lingeling in parent directory"
 
 #--------------------------------------------------------------------------#
 
